# DEPRECATED: This workflow has been replaced by deploy.yml
# Safe to delete this file.
name: "[DEPRECATED] Static"
on: workflow_dispatch
jobs:
  noop:
    if: false
    runs-on: ubuntu-latest
    steps:
      - run: echo "deprecated"
